"""Typed contracts for skill synthesis input and output."""

from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, field_validator

from skill_learner.extraction import SourceSpan, StepConfidence

_SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class SkillMetadata(BaseModel):
    """Frontmatter metadata for a generated skill."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=64)
    description: str = Field(min_length=1, max_length=1024)
    compatibility: str | None = Field(default=None, max_length=500)

    @field_validator("name")
    @classmethod
    def validate_name(cls, value: str) -> str:
        if "--" in value:
            raise ValueError("skill name must not contain consecutive hyphens")
        if value.startswith("-") or value.endswith("-"):
            raise ValueError("skill name must not start or end with hyphen")
        if _SKILL_NAME_RE.fullmatch(value) is None:
            raise ValueError("skill name must use lowercase letters, numbers, and hyphens")
        return value


class PreviewStep(BaseModel):
    """A step item from phase-2 extraction preview."""

    model_config = ConfigDict(extra="forbid")

    source_id: str = Field(min_length=3, max_length=128, pattern=r"^[a-z0-9_]+$")
    text: str = Field(min_length=1)
    tags: list[str] = Field(default_factory=list)
    confidence: StepConfidence
    span: SourceSpan | None = None
    preconditions: list[str] = Field(default_factory=list)
    postconditions: list[str] = Field(default_factory=list)


class PreviewItem(BaseModel):
    """One source-level entry from preview JSON."""

    model_config = ConfigDict(extra="allow")

    id: str = Field(min_length=1)
    source_id: str | None = None
    status: str = Field(pattern=r"^(success|failed)$")
    steps: list[PreviewStep] | None = None


class PreviewPayload(BaseModel):
    """Root schema for preview JSON used by synthesis."""

    model_config = ConfigDict(extra="allow")

    benchmark_id: str = Field(min_length=1)
    items: list[PreviewItem] = Field(default_factory=list)


class SelectedStep(BaseModel):
    """Candidate step selected for skill synthesis output."""

    model_config = ConfigDict(extra="forbid")

    source_item_id: str
    source_id: str
    text: str
    tags: list[str]
    confidence: StepConfidence
    span: SourceSpan | None = None
    preconditions: list[str] = Field(default_factory=list)
    postconditions: list[str] = Field(default_factory=list)


class SkillSynthesisResult(BaseModel):
    """Artifacts generated by synthesis workflow."""

    model_config = ConfigDict(extra="forbid")

    skill_dir: str
    skill_md_path: str
    reference_path: str
    selected_step_count: int
    validation_ran: bool
    validation_ok: bool

    @property
    def skill_dir_path(self) -> Path:
        return Path(self.skill_dir)
